services:
  booking-postgresql:
    container_name: booking-psql
    image: postgres:17
    environment:
      POSTGRES_USER: ${BOOKING_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${BOOKING_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${BOOKING_POSTGRES_DB:-postgres}
    ports:
      - "5430:5432"
    volumes:
      - booking_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BOOKING_POSTGRES_USER} -d ${BOOKING_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications-postgresql:
    container_name: notifications-psql
    image: postgres:17
    environment:
      POSTGRES_USER: ${NOTIFICATIONS_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${NOTIFICATIONS_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${NOTIFICATIONS_POSTGRES_DB:-postgres}
    ports:
      - "5431:5432"
    volumes:
      - notifications_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NOTIFICATIONS_POSTGRES_USER} -d ${NOTIFICATIONS_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.8
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  booking-migrator:
    container_name: booking-migrator
    build:
      context: ./migrator
    environment:
      POSTGRES_URL: ${BOOKING_DB_URL}
      MIGRATIONS_PATH: ${BOOKING_MIGRATIONS_PATH}
    depends_on:
      booking-postgresql:
        condition: service_healthy

  notifications-migrator:
    container_name: notifications-migrator
    build:
      context: ./migrator
    environment:
      POSTGRES_URL: ${NOTIFICATIONS_DB_URL}
      MIGRATIONS_PATH: ${NOTIFICATIONS_MIGRATIONS_PATH}
    depends_on:
      notifications-postgresql:
        condition: service_healthy

  booking-api:
    container_name: booking-api
    build:
      context: ./booking
    environment:
      POSTGRES_URL: ${BOOKING_DB_URL}
    volumes:
      - ./booking/configs/config.yml:/app/config.yml:ro
    ports:
      - "8080:8080"

  notifications-service:
    container_name: notifications-service
    build:
      context: ./notifications
    environment:
      POSTGRES_URL: ${NOTIFICATIONS_DB_URL}
    volumes:
      - ./notifications/configs/config.yml:/app/config.yml:ro

volumes:
  booking_db:
  notifications_db: