server:
  port: 8080
  host: 0.0.0.0
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 60s
  shutdown_timeout: 30s

postgres:
  max_conns: 25
  max_lifetime: 1h

logger:
  level: debug
  format: text

ticker:
  slot_interval: 1h
  tick_interval: 1h

jwt_token:
  exp: 1h
  iss: booking-api
  